install(FILES
    ${CMAKE_CURRENT_SOURCE_DIR}/${PROJECT_NAME}.init
    DESTINATION /etc/init.d
    RENAME ${PROJECT_NAME}
    PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE
)
install(FILES
    ${CMAKE_CURRENT_SOURCE_DIR}/${PROJECT_NAME}.env
    DESTINATION /etc/conf.d
    RENAME ${PROJECT_NAME}
    PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ
)
